GET http://localhost:5000/api/players

###
GET http://localhost:5000/api/players/3

###
POST http://localhost:5000/api/players
Content-Type: application/json

{
    "name":"Frank Ribery",
    "age":30,
    "nationalityId":1,
    "positions":[{"id" : 2}, {"id" : 3}],
    "height":178,
    "weight":73,
    "pac":20,
    "tec":18,
    "dri":20,
    "fin":19,
    "pas":16
}

###
PUT http://localhost:5000/api/players/3
Content-Type: application/json

{
    "id": 3,
    "name":"Sergio Agüero",
    "age":30,
    "nationalityId":2,
    "positions": [{"id" : 2}],
    "height":178,
    "weight":73,
    "pac":20,
    "tec":18,
    "dri":20,
    "fin":19,
    "pas":16
}

###
DELETE http://localhost:5000/api/players/2
